var data = [
	"Sajt",
	"Valami",
	"Asdf",
	"Valaki",
	"Mas Valaki"
]

var simpleNamesArray = [
	"Bársony Árpád",
	"Bodnár Réka",
	"Donkó István",
	"Eleki Rebeka",
	"Erdei Zsuzsanna",
	"Fábián Bálint",
	"Farkas Lívia",
	"Faragó Miklós",
	"Fazekas Noémi",
	"Fülöp Dániel",
	"Gazdag Sándor",
	"Geiszl András",
	"Gremsperger Júlia",
	"Inges Tamás",
	"Kerékgyártó Judit",
	"Márton Dorina",
	"Molnár Lilla",
	"Muzslay Eszter",
	"Nagy Krisztián",
	"Nyeste Tódor",
	"Osztobányi Lilla",
	"Plánk Fanni",
	"Sali Ádám",
	"Stauder Dóra",
	"Szakács Norbert",
	"Szánthó Zselyke",
	"Székely Réka",
	"Szecső Patrícia",
	"Szerző Ágoston",
	"Szujó Tamás",
	"Szűcs Dalma",
	"Tarján Hedvig",
	"Teveli Evelin",
	"Vida Franciska",
	"Wächter Baldó",
	"Zacher Bendegúz"
];

var namesArray = [
	"Bársony Árpád",
	"Bodnár Réka",
	"Donkó István",
	"Eleki Rebeka",
	"Erdei Zsuzsanna",
	"Fábián Bálint",
	"Farkas Lívia",
	"Faragó Miklós",
	"Fazekas Noémi",
	"Fülöp Dániel István",
	"Gazdag Sándor",
	"Geiszl András",
	"Gremsperger Júlia",
	"Inges Tamás",
	"Kerékgyártó Judit",
	"Márton Dorina",
	"Molnár Lilla",
	"Muzslay Eszter",
	"Nagy Krisztián Péter",
	"Nyeste Tódor Dávid",
	"Osztobányi Lilla Eszter",
	"Plánk Fanni",
	"Sali Ádám",
	"Stauder Dóra",
	"Szakács Norbert Hunor",
	"Szánthó Zselyke Júlia",
	"Székely Réka",
	"Szecső Patrícia",
	"Szerző Ágoston",
	"Szujó Tamás",
	"Szűcs Dalma Susanne",
	"Tarján Hedvig",
	"Teveli Evelin Vanessa",
	"Vida Franciska",
	"Wächter Baldó",
	"Zacher Ádám Bendegúz"
];